apiVersion: batch/v1
kind: Job
metadata:
  name: app
  labels:
    app.kubernetes.io/component: job
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      serviceAccountName: app-sa
      restartPolicy: Never
      containers:
        - name: app
          image: PLACEHOLDER_IMAGE:PLACEHOLDER_TAG
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL

