apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "<ZONE_LABEL_KEY>"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: app

