apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app
  labels:
    app.kubernetes.io/component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: PLACEHOLDER_MIN_REPLICAS
  maxReplicas: PLACEHOLDER_MAX_REPLICAS
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: PLACEHOLDER_CPU_TARGET

