apiVersion: batch/v1
kind: CronJob
metadata:
  name: app
  labels:
    app.kubernetes.io/component: cronjob
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: app-sa
          restartPolicy: OnFailure
          containers:
            - name: app
              image: PLACEHOLDER_IMAGE:PLACEHOLDER_TAG
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                runAsNonRoot: true
                runAsUser: 1000
                capabilities:
                  drop:
                    - ALL

